import Link from "next/link";
import { redirect } from "next/navigation";
import { SlotlyLogo } from "@/src/components/slotly-logo";
import { ThemeToggle } from "@/src/components/theme-toggle";
import { getCustomerBookings } from "@/src/lib/customer-data";

export default async function CustomerAccountPage() {
  const bookings = await getCustomerBookings();
  if (!bookings) redirect("/login?next=/account");
  return <main id="main-content" className="min-h-screen bg-[var(--paper)]"><header className="border-b border-[var(--line)] bg-[var(--card)]"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-5 lg:px-8"><SlotlyLogo /><div className="flex items-center gap-2"><ThemeToggle /><Link href="/" className="focus-ring rounded-full border border-[var(--line)] px-4 py-2 text-sm font-bold">Найти специалиста</Link></div></div></header><section className="mx-auto max-w-5xl px-5 py-12 lg:px-8"><p className="eyebrow">Личный кабинет клиента</p><h1 className="display mt-3 text-5xl font-bold">Ваши записи</h1><p className="mt-3 text-[var(--muted)]">Здесь собраны подтверждения и детали будущих визитов.</p><div className="mt-8 space-y-4">{bookings.length ? bookings.map((booking) => <article key={booking.id} className="surface flex flex-wrap items-start justify-between gap-4 p-6"><div><p className="text-sm font-semibold text-[var(--accent)]">{new Date(`${booking.date}T12:00:00`).toLocaleDateString("ru-RU", { day: "numeric", month: "long" })} · {booking.time}</p><h2 className="display mt-2 text-2xl font-bold">{booking.serviceName}</h2><p className="mt-2 text-sm text-[var(--muted)]">Номер записи: {booking.reference}</p></div><span className="rounded-full bg-[var(--mint)] px-3 py-1.5 text-xs font-bold text-[var(--brand)]">{booking.status === "confirmed" ? "Подтверждена" : booking.status === "cancelled" ? "Отменена" : "Ожидает подтверждения"}</span></article>) : <div className="surface p-10 text-center"><h2 className="display text-3xl font-bold">Пока нет записей</h2><p className="mt-3 text-[var(--muted)]">Найдите специалиста и забронируйте удобное время.</p><Link href="/" className="mt-6 inline-block rounded-full bg-[var(--accent)] px-5 py-3 font-bold text-white">Перейти в каталог</Link></div>}</div></section></main>;
}
