import Image from "next/image";
import Link from "next/link";
import { getCategoryLabel, profileCategories } from "@/src/lib/catalog";
import { getCatalogProfiles } from "@/src/lib/owner-data";
import { SlotlyLogo } from "@/src/components/slotly-logo";
import { ThemeToggle } from "@/src/components/theme-toggle";

type SearchParams = Promise<{ query?: string; category?: string; city?: string }>;

const benefits = [
  ["Онлайн-запись 24/7", "Клиент выбирает свободное окно тогда, когда ему удобно."],
  ["Личная страница", "Ссылка с услугами, условиями и понятным путём к записи."],
  ["Расписание", "Все рабочие часы и перерывы собраны в одном календаре."],
  ["Управление услугами", "Цена, категория, длительность и фото всегда актуальны."],
  ["Статусы записей", "Новые, подтверждённые и отменённые визиты не теряются."],
  ["Работает с телефона", "Клиент записывается, а специалист управляет днём откуда угодно."],
];

export default async function HomePage({ searchParams }: { searchParams: SearchParams }) {
  const filters = await searchParams;
  const profiles = await getCatalogProfiles(filters);
  const activeCategory = filters.category ?? "";
  const shownProfiles = profiles.slice(0, 4);

  return <main className="min-h-screen bg-[var(--paper)]">
    <nav className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 lg:px-8">
      <SlotlyLogo />
      <div className="hidden items-center gap-8 text-sm font-semibold md:flex"><a href="#catalog">Возможности</a><a href="#specialists">Для кого</a><a href="#how-it-works">Как это работает</a><Link href="/account">Мои записи</Link><Link href="/login">Войти</Link></div>
      <div className="flex items-center gap-2"><ThemeToggle /><Link href="/account" className="hidden text-sm font-bold text-[var(--brand)] sm:inline">Мой кабинет</Link><Link href="/register?role=customer" className="slotly-button px-4">Начать бесплатно</Link></div>
    </nav>

    <section className="hero-stage min-h-[34rem] border-y border-[var(--line)]">
      <Image src="/slotly-desk-scene.png" alt="Рабочее место с календарём, свободным временем и настольными часами" width={1536} height={864} priority className="hero-stage__scene" />
      <div className="mx-auto grid max-w-6xl gap-8 px-5 py-14 lg:grid-cols-[.9fr_1.1fr] lg:px-8 lg:py-20">
        <div className="self-center rounded-2xl bg-white/85 p-5 text-[#17191d] shadow-[0_12px_28px_rgb(73_55_24_/_0.1)] backdrop-blur-[2px] sm:p-7"><p className="inline-flex rounded-full bg-[#f5f3ed] px-3 py-1 text-xs font-bold text-[#17191d]">Онлайн-запись без лишних переписок</p><h1 className="display mt-5 max-w-xl text-5xl sm:text-6xl">Найдите время<br />для хорошего дела.</h1><p className="mt-7 max-w-lg text-sm leading-6 text-[#4f535c] sm:text-base">Выбирайте специалиста рядом, смотрите условия и бронируйте онлайн. Без звонков и долгих переписок.</p>
          <form action="/" className="mt-6 grid max-w-xl overflow-hidden rounded-xl border border-white/70 bg-white/90 p-1.5 shadow-lg shadow-stone-900/10 sm:grid-cols-[1.25fr_.85fr_auto]"><label className="grid gap-1 px-3 py-2 sm:border-r sm:border-[var(--line)]"><span className="text-[10px] font-bold uppercase tracking-wide text-[var(--muted)]">Услуга</span><input name="query" defaultValue={filters.query} placeholder="Маникюр, консультация, ремонт" className="min-w-0 bg-transparent text-xs outline-none" /></label><label className="grid gap-1 border-t border-[var(--line)] px-3 py-2 sm:border-t-0 sm:border-r"><span className="text-[10px] font-bold uppercase tracking-wide text-[var(--muted)]">Город</span><input name="city" defaultValue={filters.city} placeholder="Новосибирск" className="min-w-0 bg-transparent text-xs outline-none" /></label>{activeCategory && <input type="hidden" name="category" value={activeCategory} />}<button className="slotly-button m-0.5 px-5">Найти</button></form>
          <div className="mt-4 flex flex-wrap gap-2">{profileCategories.slice(0, 5).map((category) => <Link key={category.value} href={`/?category=${category.value}`} className="rounded-full border border-[#c9cdd5] bg-white/90 px-3 py-1.5 text-xs font-semibold text-[#17191d] transition hover:border-[var(--brand)] hover:text-[var(--brand)]">{category.label}</Link>)}</div>
        </div>
        <div className="hidden min-h-[26rem] items-center justify-end lg:flex"><div className="hero-float w-[21rem] rotate-[2deg] rounded-2xl border border-white/80 bg-white/95 p-5 shadow-2xl shadow-stone-900/15"><div className="flex items-center gap-3"><div className="h-12 w-12 rounded-full border border-[var(--line)] bg-[var(--soft)] bg-contain bg-center bg-no-repeat" style={{ backgroundImage: "url('/slotly-mark.png')" }} aria-hidden="true" /><div><p className="font-bold">Свободное окно</p><p className="mt-1 text-xs text-[var(--muted)]">Условия заранее</p></div></div><div className="mt-5 grid grid-cols-2 gap-2 text-xs"><div className="rounded-xl bg-[var(--soft)] p-3"><p className="text-[var(--muted)]">Сегодня</p><strong className="mt-1 block text-lg">18:30</strong></div><div className="rounded-xl bg-[var(--soft)] p-3"><p className="text-[var(--muted)]">Формат</p><strong className="mt-1 block text-lg">Онлайн</strong></div></div><button className="slotly-button mt-5 w-full">Выбрать время</button></div></div>
      </div>
    </section>

    <section id="catalog" className="mx-auto max-w-6xl px-5 py-16 lg:px-8 lg:py-20"><div className="flex flex-wrap items-end justify-between gap-4"><div><h2 className="display text-3xl sm:text-4xl">Специалисты, к которым хочется вернуться.</h2><p className="mt-3 text-sm text-[var(--muted)]">Выбирайте по услуге, городу и свободному времени.</p></div><Link href="/" className="text-sm font-bold text-[var(--brand)]">Все специалисты →</Link></div>
      <div className="filter-scroller mt-6"><div className="flex min-w-max gap-2"><Link href="/" className={`rounded-full border px-4 py-2 text-xs font-bold ${!activeCategory ? "border-[var(--brand)] bg-[var(--brand)] text-white" : "border-[var(--line)] bg-[var(--card)] text-[var(--muted)]"}`}>Все услуги</Link>{profileCategories.map((category) => <Link key={category.value} href={`/?category=${category.value}`} className={`rounded-full border px-4 py-2 text-xs font-bold transition ${activeCategory === category.value ? "border-[var(--brand)] bg-[var(--brand)] text-white" : "border-[var(--line)] bg-[var(--card)] text-[var(--muted)] hover:border-[var(--brand)]"}`}>{category.label}</Link>)}</div></div>
      {shownProfiles.length ? <div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{shownProfiles.map((profile) => <Link key={profile.id} href={`/p/${profile.slug}`} className="group overflow-hidden rounded-xl border border-[var(--line)] bg-[var(--card)] transition duration-200 hover:-translate-y-1 hover:border-[var(--brand)]"><div className="relative aspect-[4/3] bg-[#d9d2c4] bg-cover bg-center" style={profile.coverPath || profile.avatarPath ? { backgroundImage: `url(${profile.coverPath || profile.avatarPath})` } : undefined}>{!(profile.coverPath || profile.avatarPath) && <div className="grid h-full place-items-center bg-[var(--soft)] text-5xl font-bold text-[var(--brand)]">{profile.name.slice(0, 1)}</div>}<span className="absolute bottom-2 right-2 rounded-full border border-[var(--line)] bg-[var(--card)] px-2 py-1 text-[10px] font-bold text-[var(--ink)]">{profile.city || "Онлайн"}</span></div><div className="p-4"><p className="text-xs font-semibold text-[var(--brand)]">{getCategoryLabel(profile.category)}</p><h3 className="mt-2 text-lg font-extrabold tracking-[-.03em]">{profile.name}</h3><p className="mt-1 line-clamp-1 text-xs text-[var(--muted)]">{profile.description}</p><div className="mt-4 space-y-1.5">{profile.services.slice(0, 2).map((service) => <div key={service.id} className="flex items-center justify-between rounded-lg bg-[var(--soft)] px-2.5 py-1.5 text-[10px]"><span className="truncate pr-2">{service.name}</span><strong>{service.priceLabel || "—"}</strong></div>)}</div></div></Link>)}</div> : <div className="mt-7 rounded-xl border border-dashed border-[var(--line)] bg-[var(--card)] p-10 text-center"><h3 className="text-xl font-bold">Ничего не нашли</h3><p className="mt-2 text-sm text-[var(--muted)]">Попробуйте изменить услугу или город.</p><Link href="/" className="mt-4 inline-block text-sm font-bold text-[var(--brand)]">Сбросить фильтры</Link></div>}</section>

    <section id="how-it-works" className="mx-auto max-w-6xl px-5 pb-20 lg:px-8"><h2 className="display text-3xl sm:text-4xl">Как это работает</h2><div className="mt-7 grid gap-4 md:grid-cols-3">{[["1", "Создайте страницу", "Добавьте услуги, цены и рабочее время."], ["2", "Настройте расписание", "Укажите свободные окна в календаре."], ["3", "Принимайте заявки", "Новые записи появятся в кабинете автоматически."]].map(([number, title, text]) => <article key={number} className="surface p-5"><span className="grid h-7 w-7 place-items-center rounded-full bg-[var(--brand)] text-xs font-bold text-white">{number}</span><h3 className="mt-8 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{text}</p></article>)}</div></section>

    <section id="specialists" className="border-y border-[var(--line)] bg-white/55 px-5 py-16 lg:px-8"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[.68fr_1.32fr]"><div className="self-center"><p className="text-sm font-bold text-[var(--brand)]">Для специалистов</p><h2 className="display mt-4 text-4xl">Соберите запись в одном месте.</h2><p className="mt-5 max-w-md leading-7 text-[var(--muted)]">Профиль, услуги, календарь и заявки. Всё, что помогает работать спокойно.</p><Link href="/for-specialists" className="slotly-button mt-7 px-5">Посмотреть кабинет →</Link></div><div className="rounded-2xl border border-[var(--line)] bg-[var(--card)] p-4 shadow-lg shadow-stone-900/5 sm:p-6"><div className="flex items-center gap-5"><SlotlyLogo compact /><div><p className="font-bold">Добрый день, Александр</p><p className="mt-1 text-xs text-[var(--muted)]">Вот что происходит сегодня.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{[["6", "Записей сегодня"], ["24", "Клиентов на неделе"], ["9", "Свободных окон"]].map(([value, label]) => <div key={label} className="rounded-xl border border-[var(--line)] p-3"><strong className="text-xl">{value}</strong><span className="mt-1 block text-[11px] text-[var(--muted)]">{label}</span></div>)}</div><div className="mt-5 overflow-hidden rounded-xl border border-[var(--line)]"><div className="grid grid-cols-[64px_repeat(5,1fr)] text-[10px]"><div className="border-r border-[var(--line)] p-2 text-[var(--muted)]">Время</div>{["Пн", "Вт", "Ср", "Чт", "Пт"].map((day) => <div key={day} className="border-r border-[var(--line)] p-2 text-center font-bold last:border-r-0">{day}</div>)}{["10:00", "12:00", "14:00", "16:00"].flatMap((time, row) => [<div key={`${time}-t`} className="border-r border-t border-[var(--line)] p-2 text-[var(--muted)]">{time}</div>, ...[0, 1, 2, 3, 4].map((day) => <div key={`${time}-${day}`} className={`min-h-9 border-r border-t border-[var(--line)] p-1 last:border-r-0 ${row === day % 4 ? "bg-[var(--mint)]" : ""}`}>{row === day % 4 && <span className="block rounded bg-[var(--brand)] px-1 py-0.5 text-center text-[8px] text-white">Запись</span>}</div>)])}</div></div></div></div></section>

    <section className="mx-auto max-w-6xl px-5 py-16 lg:px-8"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{benefits.map(([title, text]) => <article key={title} className="rounded-xl border border-[var(--line)] bg-[var(--card)] p-5"><div className="h-1.5 w-8 rounded-full bg-[var(--brand)]" /><h3 className="mt-5 font-bold">{title}</h3><p className="mt-2 text-sm leading-6 text-[var(--muted)]">{text}</p></article>)}</div><div className="home-cta mt-12 flex flex-col justify-between gap-5 rounded-2xl p-7 sm:flex-row sm:items-center"><div><h2 className="display text-3xl">Начните принимать записи уже сегодня.</h2><p className="mt-3 text-sm text-[var(--muted)]">Создайте страницу Slotly за несколько минут и отправьте её первому клиенту.</p></div><Link href="/register?role=specialist" className="slotly-button shrink-0 px-5">Начать бесплатно</Link></div></section>

    <footer className="mx-auto flex max-w-6xl flex-wrap items-center justify-between gap-4 border-t border-[var(--line)] px-5 py-8 text-xs text-[var(--muted)] lg:px-8"><SlotlyLogo /><p>© {new Date().getFullYear()} Slotly. Все права защищены.</p><div className="flex gap-4"><Link href="/for-specialists">Для специалистов</Link><Link href="/login">Войти</Link></div></footer>
  </main>;
}
