import Image from "next/image";
import Link from "next/link";
import { getCategoryLabel, profileCategories } from "@/src/lib/catalog";
import { getCatalogProfiles } from "@/src/lib/owner-data";
import { SlotlyLogo } from "@/src/components/slotly-logo";
import { ThemeToggle } from "@/src/components/theme-toggle";

type SearchParams = Promise<{ query?: string; category?: string; city?: string }>;

export default async function HomePage({ searchParams }: { searchParams: SearchParams }) {
  const filters = await searchParams;
  const profiles = await getCatalogProfiles(filters);
  const activeCategory = filters.category ?? "";
  return <main className="consumer-theme min-h-screen bg-[var(--paper)]">
    <nav className="mx-auto flex max-w-[1400px] items-center justify-between border-b border-[var(--line)] px-5 py-5 lg:px-12"><SlotlyLogo /><div className="flex items-center gap-3 text-sm font-bold"><Link href="/for-specialists" className="hidden text-[var(--muted)] sm:block">Для специалистов</Link><ThemeToggle /><Link href="/register" className="rounded-full bg-[var(--accent)] px-4 py-2 text-white">Создать профиль</Link></div></nav>
    <section className="mx-auto grid max-w-[1400px] gap-10 px-5 py-16 lg:grid-cols-[.9fr_1.1fr] lg:px-12 lg:py-28"><div><p className="eyebrow">Запись в нужные руки</p><h1 className="display mt-5 text-6xl font-bold leading-[.9] sm:text-8xl">Найдите время<br />для хорошего дела.</h1><p className="mt-8 max-w-xl text-lg leading-8 text-[var(--muted)]">Выбирайте специалиста рядом, смотрите условия и бронируйте онлайн. Без звонков и долгих переписок.</p><form action="/" className="mt-10 grid overflow-hidden rounded-2xl border border-[var(--line)] bg-[var(--card)] shadow-xl shadow-black/5 sm:grid-cols-[1.3fr_.7fr_auto]"><label className="grid gap-1 border-b border-[var(--line)] px-5 py-4 sm:border-b-0 sm:border-r"><span className="text-xs font-bold text-[var(--muted)]">Услуга</span><input name="query" defaultValue={filters.query} placeholder="Маникюр, консультация, ремонт" className="bg-transparent text-sm outline-none" /></label><label className="grid gap-1 border-b border-[var(--line)] px-5 py-4 sm:border-b-0 sm:border-r"><span className="text-xs font-bold text-[var(--muted)]">Город</span><input name="city" defaultValue={filters.city} placeholder="Новосибирск" className="bg-transparent text-sm outline-none" /></label>{activeCategory && <input type="hidden" name="category" value={activeCategory} />}<button className="m-2 rounded-xl bg-[var(--accent)] px-5 py-3 text-sm font-bold text-white">Найти</button></form><div className="mt-5 flex flex-wrap gap-2">{profileCategories.slice(0, 5).map((category) => <Link key={category.value} href={`/?category=${category.value}`} className="rounded-full border border-[var(--line)] px-3 py-1.5 text-xs font-semibold text-[var(--muted)]">{category.label}</Link>)}</div></div><div className="relative min-h-[27rem] overflow-hidden rounded-[32px] bg-[#d8c8b7]"><Image src="/slotly-marketplace-preview.png" alt="Онлайн-запись в Slotly" width={1488} height={1024} className="h-full w-full object-cover object-[58%_center]" priority /><div className="absolute bottom-5 right-5 rounded-2xl border border-white/60 bg-[#fffdf9e8] p-4 text-[#1f2522] backdrop-blur"><p className="text-xs text-[#6e746d]">Свободное окно</p><strong className="display text-2xl">Сегодня, 18:30</strong><p className="mt-1 text-xs">Цена и длительность заранее</p></div></div></section>
    <section className="mx-auto max-w-[1400px] px-5 pb-20 lg:px-12"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="eyebrow">Каталог</p><h2 className="display mt-4 text-5xl font-bold">Специалисты, к которым хочется вернуться.</h2></div><p className="text-sm text-[var(--muted)]">{profiles.length} профилей</p></div><div className="mt-8 flex gap-2 overflow-auto pb-2"><Link href="/" className={`whitespace-nowrap rounded-full border px-4 py-2 text-sm font-semibold ${!activeCategory ? "border-[var(--accent)] bg-[var(--soft)] text-[var(--accent-dark)]" : "border-[var(--line)] text-[var(--muted)]"}`}>Все услуги</Link>{profileCategories.map((category) => <Link key={category.value} href={`/?category=${category.value}`} className={`whitespace-nowrap rounded-full border px-4 py-2 text-sm font-semibold ${activeCategory === category.value ? "border-[var(--accent)] bg-[var(--soft)] text-[var(--accent-dark)]" : "border-[var(--line)] text-[var(--muted)]"}`}>{category.label}</Link>)}</div>{profiles.length ? <div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{profiles.map((profile) => <Link key={profile.id} href={`/p/${profile.slug}`} className="overflow-hidden rounded-3xl border border-[var(--line)] bg-[var(--card)] transition hover:-translate-y-1 hover:border-[var(--accent)]"><div className="grid aspect-[16/9] place-items-center bg-[#d8c8b7] bg-cover bg-center text-5xl font-bold text-white" style={profile.coverPath ? { backgroundImage: `url(${profile.coverPath})` } : undefined}>{profile.coverPath ? "" : profile.name.slice(0, 1)}</div><div className="p-5"><p className="text-xs font-bold uppercase tracking-wider text-[var(--accent)]">{getCategoryLabel(profile.category)} · {profile.city || "Онлайн"}</p><h3 className="display mt-3 text-3xl font-bold">{profile.name}</h3><p className="mt-3 line-clamp-2 text-sm leading-6 text-[var(--muted)]">{profile.description}</p><div className="mt-5 border-t border-[var(--line)] pt-3 text-sm">{profile.services.slice(0, 2).map((service) => <p key={service.id} className="flex justify-between py-1"><span>{service.name}</span><strong>{service.priceLabel || "по запросу"}</strong></p>)}</div></div></Link>)}</div> : <div className="mt-8 rounded-3xl border border-[var(--line)] bg-[var(--card)] p-14 text-center"><h3 className="display text-3xl font-bold">Ничего не нашли</h3><p className="mt-3 text-[var(--muted)]">Попробуйте другой запрос или сбросьте фильтры.</p><Link href="/" className="mt-6 inline-block font-bold text-[var(--accent-dark)]">Сбросить фильтры</Link></div>}</section>
    <section className="bg-[#1f2522] px-5 py-20 text-[#f5f2eb] lg:px-12"><div className="mx-auto grid max-w-[1400px] gap-12 lg:grid-cols-2"><div><p className="eyebrow">Для специалистов</p><h2 className="display mt-5 text-6xl font-bold leading-[.9]">Соберите запись<br />в одном месте.</h2><p className="mt-6 max-w-md leading-7 text-[#d5d0c6]">Профиль, услуги, календарь и заявки. Всё, что помогает работать спокойно.</p><Link href="/for-specialists" className="mt-7 inline-block font-bold text-[#ff9b84]">Посмотреть кабинет →</Link></div><ol className="grid content-center"><li className="border-b border-white/20 py-5 text-2xl"><span className="mr-5 text-xs font-bold text-[#ff9b84]">01</span>Создайте страницу</li><li className="border-b border-white/20 py-5 text-2xl"><span className="mr-5 text-xs font-bold text-[#ff9b84]">02</span>Настройте расписание</li><li className="border-b border-white/20 py-5 text-2xl"><span className="mr-5 text-xs font-bold text-[#ff9b84]">03</span>Принимайте заявки</li></ol></div></section>
  </main>;
}
