import Link from "next/link";
import { SlotlyLogo } from "@/src/components/slotly-logo";
import { ThemeToggle } from "@/src/components/theme-toggle";

const steps = [
  ["01", "Соберите страницу", "Добавьте имя, услуги, город и ссылку, которую можно отправить клиентам."],
  ["02", "Задайте свой ритм", "Укажите рабочие часы и перерывы. Slotly покажет только подходящие окна."],
  ["03", "Принимайте решения", "Подтверждайте заявки и управляйте днём без переписок в нескольких местах."],
];

export default function ForSpecialistsPage() {
  return <main id="main-content" className="min-h-screen bg-[var(--paper)]">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 lg:px-8"><SlotlyLogo /><div className="flex items-center gap-3"><Link href="/account" className="hidden text-sm font-semibold text-[var(--muted)] sm:inline">Для клиентов</Link><ThemeToggle /><Link href="/login?role=specialist" className="text-sm font-semibold text-[var(--muted)] transition hover:text-[var(--brand)]">Войти</Link><Link href="/register?role=specialist" className="rounded-full bg-[var(--brand)] px-4 py-2 text-sm font-bold text-[var(--paper)] transition hover:opacity-90">Начать бесплатно</Link></div></nav>
    <section className="mx-auto grid max-w-7xl gap-12 px-5 pb-24 pt-14 lg:grid-cols-[1.05fr_.95fr] lg:px-8 lg:pt-24"><div className="self-center"><p className="eyebrow">Slotly для специалистов</p><h1 className="display mt-5 max-w-2xl text-5xl font-bold leading-[.96] sm:text-7xl">Спокойный день начинается с ясного расписания.</h1><p className="mt-7 max-w-xl text-lg leading-8 text-[var(--muted)]">Личная страница, услуги, календарь и заявки — одно понятное место для вашей практики.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/register?role=specialist" className="rounded-full bg-[var(--accent)] px-6 py-3.5 font-bold text-white transition hover:bg-[var(--accent-dark)]">Создать профиль бесплатно</Link><Link href="/" className="rounded-full border border-[var(--line)] px-6 py-3.5 font-bold transition hover:border-[var(--brand)]">Посмотреть каталог</Link></div><p className="mt-5 text-sm text-[var(--muted)]">Без комиссий и сложной настройки.</p></div><div className="rounded-[32px] border border-[var(--line)] bg-[var(--brand)] p-3 shadow-2xl shadow-black/10"><div className="rounded-[23px] bg-[var(--card)] p-5 sm:p-7"><div className="flex items-start justify-between gap-4 border-b border-[var(--line)] pb-5"><div><p className="text-sm text-[var(--muted)]">Среда, 26 августа</p><h2 className="display mt-1 text-3xl font-bold">Сегодня в работе</h2></div><span className="rounded-full bg-[var(--mint)] px-3 py-1.5 text-xs font-bold text-[var(--brand)]">3 новые заявки</span></div><div className="mt-5 grid grid-cols-3 gap-3">{[["12", "заявок"], ["8", "подтверждено"], ["4", "свободных окна"]].map(([value, label]) => <div key={label} className="rounded-2xl border border-[var(--line)] p-3 sm:p-4"><strong className="text-2xl sm:text-3xl">{value}</strong><span className="mt-1 block text-xs leading-4 text-[var(--muted)]">{label}</span></div>)}</div><div className="mt-6 space-y-3">{[["10:00", "Мария", "Макияж · 60 мин"], ["13:30", "Никита", "Консультация · 45 мин"], ["17:00", "Анна", "Уход · 90 мин"]].map(([time, client, service]) => <div key={time} className="flex items-center gap-4 rounded-2xl bg-[var(--paper)] px-4 py-3.5"><strong className="text-sm">{time}</strong><span className="h-8 w-px bg-[var(--line)]" /><div><p className="text-sm font-bold">{client}</p><p className="text-xs text-[var(--muted)]">{service}</p></div></div>)}</div></div></div></section>
    <section className="border-y border-[var(--line)] bg-[var(--card)] px-5 py-20 lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow">Три понятных шага</p><div className="mt-8 grid gap-4 md:grid-cols-3">{steps.map(([number, title, text]) => <article key={number} className="rounded-3xl border border-[var(--line)] bg-[var(--paper)] p-6 sm:p-7"><span className="text-sm font-bold text-[var(--accent)]">{number}</span><h2 className="display mt-12 text-2xl font-bold">{title}</h2><p className="mt-3 leading-7 text-[var(--muted)]">{text}</p></article>)}</div></div></section>
  </main>;
}
