"use client";

import { useState } from "react";
import { useRouter, useSearchParams } from "next/navigation";
import { createClient } from "@/src/lib/supabase/client";

function Field({ label, ...props }: React.InputHTMLAttributes<HTMLInputElement> & { label: string }) {
  return <label className="mt-4 block text-sm font-semibold">{label}<input {...props} className="focus-ring mt-2 w-full rounded-xl border border-[var(--line)] bg-[var(--card)] px-4 py-3 font-normal outline-none transition focus:border-[var(--accent)]" /></label>;
}

export function LoginForm() {
  const router = useRouter(); const params = useSearchParams();
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); const { data, error: signInError } = await createClient().auth.signInWithPassword({ email, password }); if (signInError) { setError("Неверный email или пароль"); setLoading(false); return; } const type = data.user?.user_metadata?.account_type; router.push(params.get("next") || (type === "specialist" ? "/admin" : "/account")); router.refresh(); }
  return <form onSubmit={submit} className="mt-6"><Field label="Email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" required autoComplete="email" /><Field label="Пароль" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Минимум 6 символов" required minLength={6} autoComplete="current-password" />{error && <p role="alert" className="mt-4 rounded-xl bg-[var(--soft)] px-4 py-3 text-sm font-semibold text-[var(--accent-dark)]">{error}</p>}<button disabled={loading} className="focus-ring mt-6 w-full rounded-full bg-[var(--accent)] px-6 py-3.5 font-bold text-white transition hover:bg-[var(--accent-dark)] disabled:opacity-60">{loading ? "Входим…" : "Войти"}</button></form>;
}

type AccountType = "customer" | "specialist";
export function RegisterForm() {
  const router = useRouter(); const [accountType, setAccountType] = useState<AccountType>("customer");
  const [name, setName] = useState(""); const [slug, setSlug] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); setLoading(true); setError(""); setMessage(""); const normalizedSlug = slug.toLowerCase().trim().replace(/[^a-z0-9-]+/g, "-").replace(/^-|-$/g, ""); if (accountType === "specialist" && normalizedSlug.length < 3) { setError("Ссылка должна содержать минимум 3 латинских символа"); setLoading(false); return; } const { data, error: signUpError } = await createClient().auth.signUp({ email, password, options: { data: { display_name: name, slug: normalizedSlug || `client-${Date.now()}`, account_type: accountType } } }); if (signUpError) { setError(signUpError.message.includes("already") ? "Этот email уже зарегистрирован" : signUpError.message); setLoading(false); return; } if (data.session) { router.push(accountType === "specialist" ? "/admin" : "/account"); router.refresh(); } else { setMessage("Аккаунт создан. Проверьте почту и подтвердите email, затем войдите."); setLoading(false); } }
  return <form onSubmit={submit} className="mt-6"><fieldset><legend className="text-sm font-semibold">Как вы будете пользоваться Slotly?</legend><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" role="radio" aria-checked={accountType === "customer"} onClick={() => setAccountType("customer")} className={`focus-ring rounded-xl border px-3 py-3 text-sm font-bold transition ${accountType === "customer" ? "border-[var(--accent)] bg-[var(--soft)] text-[var(--accent-dark)]" : "border-[var(--line)] text-[var(--muted)]"}`}>Я ищу услугу</button><button type="button" role="radio" aria-checked={accountType === "specialist"} onClick={() => setAccountType("specialist")} className={`focus-ring rounded-xl border px-3 py-3 text-sm font-bold transition ${accountType === "specialist" ? "border-[var(--brand)] bg-[var(--mint)] text-[var(--brand)]" : "border-[var(--line)] text-[var(--muted)]"}`}>Я оказываю услуги</button></div></fieldset><Field label="Имя" value={name} onChange={(event) => setName(event.target.value)} placeholder={accountType === "customer" ? "Анна" : "Алина Воронова"} required minLength={2} autoComplete="name" />{accountType === "specialist" && <><Field label="Короткая ссылка" value={slug} onChange={(event) => setSlug(event.target.value)} placeholder="alina-voronova" required pattern="[A-Za-z0-9-]+" /><p className="mt-2 text-xs text-[var(--muted)]">Ваша публичная страница: /p/{slug || "ваш-slug"}</p></>}<Field label="Email" type="email" value={email} onChange={(event) => setEmail(event.target.value)} placeholder="you@example.com" required autoComplete="email" /><Field label="Пароль" type="password" value={password} onChange={(event) => setPassword(event.target.value)} placeholder="Минимум 6 символов" required minLength={6} autoComplete="new-password" />{error && <p role="alert" className="mt-4 rounded-xl bg-[var(--soft)] px-4 py-3 text-sm font-semibold text-[var(--accent-dark)]">{error}</p>}{message && <p role="status" className="mt-4 rounded-xl bg-[var(--mint)] px-4 py-3 text-sm font-semibold text-[var(--brand)]">{message}</p>}<button disabled={loading} className="focus-ring mt-6 w-full rounded-full bg-[var(--accent)] px-6 py-3.5 font-bold text-white transition hover:bg-[var(--accent-dark)] disabled:opacity-60">{loading ? "Создаём…" : accountType === "customer" ? "Создать аккаунт клиента" : "Создать профиль специалиста"}</button></form>;
}
