"use client";

import { useMemo, useState } from "react";
import type { Booking, BookingStatus } from "@/src/lib/domain";
const labels: Record<BookingStatus, string> = { new: "Новая", confirmed: "Подтверждена", cancelled: "Отменена" };
type Filter = "all" | BookingStatus | "trash";

export function BookingsManager({ initial, demo }: { initial: Booking[]; demo: boolean }) {
  const [items, setItems] = useState(initial); const [filter, setFilter] = useState<Filter>("all"); const [message, setMessage] = useState("");
  const trash = useMemo(() => items.filter((item) => item.deletedAt), [items]);
  const shown = useMemo(() => items.filter((item) => filter === "trash" ? Boolean(item.deletedAt) : !item.deletedAt && (filter === "all" || item.status === filter)), [items, filter]);
  async function update(id: string, status: BookingStatus) { if (demo) { setItems((xs) => xs.map((x) => x.id === id ? { ...x, status } : x)); return; } const response = await fetch("/api/admin/bookings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, status }) }); if (!response.ok) return setMessage("Не удалось изменить статус"); setItems((xs) => xs.map((x) => x.id === id ? { ...x, status } : x)); }
  async function moveToTrash(id: string) { const deletedAt = new Date().toISOString(); if (!demo) { const response = await fetch("/api/admin/bookings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action: "delete" }) }); if (!response.ok) return setMessage("Не удалось переместить заявку в корзину"); } setItems((xs) => xs.map((x) => x.id === id ? { ...x, deletedAt } : x)); setMessage("Заявка перемещена в корзину на 7 дней"); }
  async function restore(id: string) { if (!demo) { const response = await fetch("/api/admin/bookings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ id, action: "restore" }) }); if (!response.ok) return setMessage((await response.json().catch(() => null))?.error ?? "Не удалось восстановить заявку"); } setItems((xs) => xs.map((x) => x.id === id ? { ...x, deletedAt: undefined } : x)); setMessage("Заявка восстановлена"); }
  return <section className="surface p-6 sm:p-8"><p className="eyebrow">Записи клиентов</p><h1 className="display mt-2 text-4xl font-bold">Заявки</h1><div className="mt-7 flex flex-wrap gap-2">{(["all", "new", "confirmed", "cancelled", "trash"] as const).map((key) => <button key={key} type="button" onClick={() => setFilter(key)} className={`rounded-full px-3 py-2 text-xs font-bold ${filter === key ? "bg-[var(--brand)] text-white" : "border border-[var(--line)] text-[var(--muted)]"}`}>{key === "all" ? "Все" : key === "trash" ? `Корзина (${trash.length})` : labels[key]}</button>)}</div>{message && <p role="status" className="mt-4 text-sm text-[var(--accent-dark)]">{message}</p>}{filter === "trash" && <p className="mt-4 text-sm text-[var(--muted)]">Заявки хранятся в корзине 7 дней. После этого восстановить их нельзя.</p>}<div className="mt-6 divide-y divide-[var(--line)]">{shown.length ? shown.map((item) => <article key={item.id} className="py-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-bold">{item.time} · {item.clientName}</p><p className="mt-1 text-sm text-[var(--muted)]">{item.serviceName} · {item.phone}</p>{item.comment && <p className="mt-1 text-sm text-[var(--muted)]">{item.comment}</p>}</div><span className="text-xs text-[var(--muted)]">{item.reference}</span></div>{item.deletedAt ? <div className="mt-3 flex flex-wrap items-center gap-3"><span className="text-xs text-[var(--muted)]">Удалена {new Date(item.deletedAt).toLocaleDateString("ru-RU")}</span><button type="button" onClick={() => void restore(item.id)} className="rounded-full border border-[var(--line)] px-3 py-2 text-xs font-bold">Восстановить</button></div> : <div className="mt-3 flex flex-wrap gap-2">{item.status !== "confirmed" && <button type="button" onClick={() => void update(item.id, "confirmed")} className="rounded-full bg-[var(--brand)] px-3 py-2 text-xs font-bold text-white">Подтвердить</button>}{item.status !== "cancelled" && <button type="button" onClick={() => void update(item.id, "cancelled")} className="rounded-full border border-[var(--line)] px-3 py-2 text-xs font-bold">Отменить</button>}<button type="button" onClick={() => void moveToTrash(item.id)} className="rounded-full border border-[var(--line)] px-3 py-2 text-xs font-bold text-[var(--accent-dark)]">В корзину</button></div>}</article>) : <p className="py-10 text-center text-sm text-[var(--muted)]">Заявок нет.</p>}</div></section>;
}
