import Link from "next/link";
import { notFound } from "next/navigation";
import { BookingFlow } from "@/src/components/booking-flow";
import { SlotlyLogo } from "@/src/components/slotly-logo";
import { ThemeToggle } from "@/src/components/theme-toggle";
import { getCategoryLabel } from "@/src/lib/catalog";
import { getPublicProfile } from "@/src/lib/owner-data";

export default async function PublicProfilePage({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const data = await getPublicProfile(slug); if (!data) notFound();
  const { profile, services, availability } = data;
  return <main className="min-h-screen bg-[var(--paper)]"><nav className="mx-auto flex max-w-5xl items-center justify-between px-5 py-6 lg:px-8"><SlotlyLogo /><div className="flex items-center gap-3"><ThemeToggle /><Link href="/register" className="rounded-full border border-[var(--line)] bg-[var(--card)] px-4 py-2 text-sm font-bold transition hover:border-[var(--accent)]">Создать свой профиль</Link></div></nav><section className="mx-auto max-w-5xl px-5 pb-12 pt-8 lg:px-8 lg:pt-12"><div className="relative overflow-hidden rounded-[32px] border border-[var(--line)] bg-[linear-gradient(135deg,#f7ddcd,#fff4e9)] bg-cover bg-center p-6 sm:p-10 dark:bg-[linear-gradient(135deg,#1d304e,#17223a)]" style={profile.coverPath ? { backgroundImage: `linear-gradient(#00000055,#00000055), url(${profile.coverPath})` } : undefined}><div className={profile.coverPath ? "text-white" : ""}><div className="flex flex-wrap items-end gap-5"><div className="grid h-20 w-20 place-items-center overflow-hidden rounded-[24px] border-4 border-white/80 bg-[var(--card)] bg-cover bg-center text-3xl font-bold text-[var(--accent)]" style={profile.avatarPath ? { backgroundImage: `url(${profile.avatarPath})` } : undefined}>{profile.avatarPath ? <span className="sr-only">Аватар {profile.name}</span> : profile.name.slice(0,1)}</div><div><p className={`text-sm font-bold ${profile.coverPath ? "text-white/80" : "text-[var(--accent)]"}`}>{getCategoryLabel(profile.category ?? "other")} · {profile.city || "Онлайн"}</p><h1 className="display mt-2 text-5xl font-bold sm:text-6xl">{profile.name}</h1></div></div><p className={`mt-7 max-w-2xl text-lg leading-8 ${profile.coverPath ? "text-white/90" : "text-[var(--muted)]"}`}>{profile.description}</p>{profile.address && <p className={`mt-4 text-sm font-semibold ${profile.coverPath ? "text-white/75" : "text-[var(--muted)]"}`}>{profile.address}</p>}</div></div><div className="mt-12"><BookingFlow services={services} availability={availability} profileId={profile.id} /></div></section><footer className="mx-auto max-w-5xl px-5 py-8 text-sm text-[var(--muted)] lg:px-8">Страница создана в <Link href="/" className="font-bold text-[var(--brand)]">Slotly</Link></footer></main>;
}
